### 检测Elasticsearch是否启动成功
GET http://127.0.0.1:9200/

### 创建Elasticsearch的索引
PUT http://127.0.0.1:9200/es3

### 查询Elasticsearch中的es索引
GET http://127.0.0.1:9200/_cat/indices?v


### 删除Elasticsearch中的es索引
DELETE http://127.0.0.1:9200/es


### 判断Elasticsearch中的es索引
HEAD http://127.0.0.1:9200/es4


### 关闭Elasticsearch中的es索引
POST http://127.0.0.1:9200/es/_close

### 开启Elasticsearch中的es索引
POST http://127.0.0.1:9200/es/_open